version: '3.8'
services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - '${PORT}:${PORT}'
    healthcheck:
      test: curl --fail http://localhost:$$PORT/api/healthcheck || exit 1
      interval: 5s
      timeout: 60s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - project_simple:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
# Names our volume
volumes:
  project_simple:
